# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Melpadivinu/a60ae9b901196f9209e38a2f7d95973c/python.ipynb
"""

a = 54.67
b = int(a)
print(b)

x = True
z = False
y = int(x)
print(y)
print(int(z))



age = 20
print(age)

name = "Vinod"
print(name)

salary = 35000.50
print(salary)

is_student = True
print(is_student)

x = 10
y = 20
z = x + y

print(z)

a, b, c = 10, 20, 30

print(a)
print(b)
print(c)

t = (1,2,3,3,5)
x = 1,2,3,4
print(type(t))
print(type(x))

s = (1,2,[3,3],5)

h = "vinod"
l = list(h)
print(l)
l(5) = "l"
print(l)
b = "".join(l)
print(b)

h = "vinod"
l = list(h)
print(l)

l[4] = "l"      # Change the character at index 4

print(l)

b = "".join(l)
print(b)

age = 20
price = 99.99
z = 3 + 4j

print(age)
print(price)
print(z)

name = "Vinod"
city = 'Bangalore'

print(name)
print(city)

fruits = ["Apple", "Banana", "Mango"]

print(fruits)
print(fruits[0])

colors = ("Red", "Green", "Blue")

print(colors)

numbers = {1, 2, 3, 4}

print(numbers)

student = {
    "name": "Vinod",
    "age": 20,
    "marks": 85
}

print(student["name"])

a= 10
print(a)

a = 5.5
b = '5'
print(a+int(b))

a = 10
b = 7
a%b

a = 4
b = 3
a**b

print((4*5)-9+6/7)

print(4+(8**2)-3**2%1)

"""# New Section"""

print(4%(1+9)**2-60//(7+2))



"""**Arthematic operators**"""

a = 15
b = 5
c = 15+5
print(c)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)

a = 20
b = 6

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponent:", a ** b)

first_name = "Vinod"
last_name = "Kumar"

full_name = first_name + " " + last_name

print(full_name)

a = "vinu"
b = "madhu"
print(a+b)

l = ['one', 'two', 'three', 'four', 'five', 'six']
print(sorted(l))
print(l)