# -*- coding: utf-8 -*-
"""Another copy of DATA ANALYTICS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB9VKwZ38n2Yf5ACmbvMlGIYsozl7Qiy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.DataFrame({
    'marks':[78,56,78,65,45,46,45],
    'hours':[5,4,5,6,5,3,6]
})
print(data)
print("mean:",np.mean(data['marks']))
print("median:",np.median(data['marks']))
print("standard deviation:",np.std(data['marks']))
print("correlation:",np.corrcoef(data['marks'],data['hours']))

plt.scatter(data['hours'], data['marks'])
plt.title('Marks vs. Hours Studied')
plt.xlabel('Hours Studied')
plt.ylabel('Marks')
plt.show()
print()
plt.bar(data['hours'], data['marks'])
plt.title('Marks vs. Hours Studied')
plt.xlabel('Hours Studied')
plt.ylabel('Marks')
plt.show()
print()
mark_counts = data['marks'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(mark_counts, labels=mark_counts.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribution of Marks')
plt.axis('equal')
plt.show()

print()
plt.hist(data['marks'], bins=5, color='purple', edgecolor='black')
plt.title('Histogram of Marks')
plt.xlabel('Marks')
plt.ylabel('Frequency')
plt.show()
print()
plt.boxplot(data['marks'])
plt.title('Box Plot of Marks')
plt.ylabel('Marks')
plt.show()
print()
print("\nStatistical Summary:")
print(data.describe())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.DataFrame({
    'order_time':['5:00','6:00','7:00','8:00'],
    'delivery_time':['5:20','6:15','7:12','8:45'],
    'delivary_partner':["Vinod","sai","Madhu","Vishnu"],
    'customer_rating':[3,4,5,2],
})
print(df)
df['']

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.DataFrame({
    'order_time':['6:00','7:00','8:00','9:00'],
    'delivery_time':['6:15','7:12','8:45','9:15'],
    'delivery_partner':["Vinod","sai","Madhu","Vishnu"],
    'delivery_area':["plmr","mdp","chittor","tpt"],
    'customer_rating':[3,4,5,2]
})
print(df)
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M')
df['delivery_time'] = pd.to_datetime(df['delivery_time'],  format='%H:%M')

dt=[]*len(df['order_time'])
for i in range(len(df['order_time'])):
    dt.append(df['delivery_time'][i] -df['order_time'][i])
print(dt)
print("average delivary_time:",np.mean(dt))
print("peak order hours",df['order_time'].dt.hour.value_counts().idxmax())
print("top rated delivary partner:",df['delivery_partner'][df['customer_rating'].idxmax()])
print("most delayed area:",df['delivery_area'][dt.index(max(dt))])
plt.title("customer rating")
sns.barplot(x=df['delivery_partner'],y=df['customer_rating'])
plt.show()
plt.title("delivery time")
sns.barplot(x=df['delivery_area'],y=dt)
plt.show()
plt

