# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wcm7FCbBvpKd8LVEydVxXf3TLnagOwOc
"""



"""**Variables**

"""

name = "Vinod"
age = 20

print(name)
print(age)

a = 10
b = 20

c = a + b

print(c)

x, y, z = 10, 20, 30

print(x)
print(y)
print(z)

"""Datatype

**Integer**
"""

num = 100
print(num)
print(type(num))

"""float"""

price = 250.75

print(price)
print(type(price))

"""String"""

name = "Python"

print(name)
print(type(name))

"""Boolean"""

status = True

print(status)
print(type(status))

"""list"""

fruits = ["Apple", "Banana", "Mango"]

print(fruits)
print(type(fruits))

"""tuple"""

numbers = (10, 20, 30)

print(numbers)
print(type(numbers))

"""Sets"""

values = {1, 2, 3, 4}

print(values)
print(type(values))

"""dictionary"""

student = {
    "Name": "Vinod",
    "Age": 20
}

print(student)
print(type(student))

"""Arthametic operators"""

a = 15
b = 4

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponent:", a ** b)

"""List program"""

fruits = ["Apple", "Banana", "Mango"]

print(fruits)

"""Assess element"""

fruits = ["Apple", "Banana", "Mango"]

print(fruits[0])
print(fruits[1])
print(fruits[2])

"""Negative Indexing"""

fruits = ["Apple", "Banana", "Mango"]

print(fruits[-1])
print(fruits[-2])

"""Update list"""

fruits = ["Apple", "Banana", "Mango"]

fruits[1] = "Orange"

print(fruits)

"""ADD an element"""

fruits = ["Apple", "Banana"]

fruits.append("Mango")

print(fruits)

"""Insert an element"""

fruits = ["Apple", "Mango"]

fruits.insert(1, "Banana")

print(fruits)

"""Remove an element"""

fruits = ["Apple", "Banana", "Mango"]

fruits.remove("Banana")

print(fruits)

"""delect using pop"""

fruits = ["Apple", "Banana", "Mango"]

fruits.pop()

print(fruits)

"""find lenght"""

fruits = ["Apple", "Banana", "Mango"]

print(len(fruits))

"""cancatenet two list"""

list1 = [1, 2, 3]
list2 = [4, 5, 6]

list3 = list1 + list2

print(list3)